import type { Metadata } from "next";
import "./globals.css";
import "@/styles/fonts.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={`antialiased px-4`}>
          <Header />
          {children}
        </div>
          <Footer />
      </body>
    </html>
  );
}
